version: "3"
services:
    python_app:
        restart: always
        build: .
        container_name: "python_app"
        working_dir: "/root/"
        tty: true
        ports:
            - 8000:8000
        volumes:
            - ./app:/root/app
